<!-- BEGIN CONTAINER -->
<div class="page-container">
	<!-- BEGIN SIDEBAR -->
	<div class="page-sidebar-wrapper">
		<!-- BEGIN SIDEBAR -->
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<div class="page-sidebar navbar-collapse collapse">
			<!-- BEGIN SIDEBAR MENU -->
			<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
			<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
			<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
			<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
			<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
			<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
			<ul class="page-sidebar-menu  page-header-fixed "
				data-keep-expanded="false" data-auto-scroll="true"
				data-slide-speed="200" style="padding-top: 20px">
				<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
				<li class="sidebar-toggler-wrapper hide">
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
					<div class="sidebar-toggler"></div> <!-- END SIDEBAR TOGGLER BUTTON -->
				</li>
				<!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
				<li class="sidebar-search-wrapper">
					<!-- BEGIN RESPONSIVE QUICK SEARCH FORM --> <!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
					<!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
					<form class="sidebar-search  " action="page_general_search_3.html"
						method="POST">
						<a href="javascript:;" class="remove"> <i class="icon-close"></i>
						</a>
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Tìm kiếm">
							<span class="input-group-btn"> <a href="javascript:;"
								class="btn submit"> <i class="icon-magnifier"></i>
							</a>
							</span>
						</div>
					</form> <!-- END RESPONSIVE QUICK SEARCH FORM -->
				</li>









				<li class="nav-item start "><a
					href="<?php echo $this->url('home').'admincp'; ?>"
					class="nav-link nav-toggle"> <i class="icon-home"></i> <span
						class="title">Trang chủ</span>
				</a></li>

				<li class="nav-item  "><a href="javascript:;"
					class="nav-link nav-toggle"> <i class="icon-user"></i> <span
						class="title">Thành viên</span> <span class="arrow"></span>
				</a>
					<ul class="sub-menu">
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/member') ?>"
							class="nav-link "> <i class="icon-users"></i> <span class="title">Danh
									sách thành viên</span>
						</a></li>
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/member', array('action'=>'add')) ?>"
							class="nav-link "> <i class="icon-user-follow"></i> <span
								class="title">Thêm thành viên</span>
						</a></li>
					</ul></li>

				<li class="nav-item  "><a href="<?php echo $this->url('admin-control-panel/category') ?>"
					class="nav-link nav-toggle"> <i class="fa fa-sitemap"></i> <span
						class="title">Danh mục</span>
				</a></li>

				<li class="nav-item  "><a href="javascript:;"
					class="nav-link nav-toggle"> <i class="icon-basket"></i> <span
						class="title">Đơn hàng</span> <span class="arrow"></span>
				</a>
					<ul class="sub-menu">
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/order') ?>"
							class="nav-link "> <i class="icon-basket-loaded"></i> <span
								class="title">Danh sách đơn hàng</span>
						</a></li>
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/category', array('action'=>'add')) ?>"
							class="nav-link "> <i class="icon-bar-chart"></i> <span
								class="title">Thống kê</span>
						</a></li>
					</ul></li>

				<li class="nav-item  "><a href="javascript:;"
					class="nav-link nav-toggle"> <i class="icon-grid"></i> <span
						class="title">Sản phẩm</span> <span class="arrow"></span>
				</a>
					<ul class="sub-menu">
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/product') ?>"
							class="nav-link "> <i class="fa fa-th-list"></i> <span
								class="title">Danh sách sản phẩm</span>
						</a></li>
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/product', array('action'=>'add')) ?>"
							class="nav-link "> <i class="icon-login"></i> <span class="title">Thêm
									sản phẩm mới</span>
						</a></li>
					</ul></li>

				<li class="nav-item  "><a href="javascript:;"
					class="nav-link nav-toggle"> <i class="icon-note"></i> <span
						class="title">Bài viết</span> <span class="arrow"></span>
				</a>
					<ul class="sub-menu">
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/post') ?>"
							class="nav-link "> <i class="icon-notebook"></i> <span
								class="title">Danh sách bài viết</span>
						</a></li>
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/post', array('action'=>'add')) ?>"
							class="nav-link "> <i class="icon-pencil"></i> <span
								class="title">Thêm bài viết mới</span>
						</a></li>
					</ul></li>
                
                <li class="nav-item  "><a href="<?php echo $this->url('admin-control-panel/link') ?>"
					class="nav-link nav-toggle"> <i class="fa fa-link"></i> <span
						class="title">Đường dẫn</span>
				</a></li>
                
				<li class="nav-item  "><a href="javascript:;"
					class="nav-link nav-toggle"> <i class="icon-folder"></i> <span
						class="title">Tập tin</span> <span class="arrow"></span>
				</a>
					<ul class="sub-menu">
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/file') ?>"
							class="nav-link "> <i class="icon-docs"></i> <span class="title">Danh
									sách tập tin</span>
						</a></li>
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/file', array('action'=>'list-all-shared')) ?>"
							class="nav-link "> <i class="icon-docs"></i> <span class="title">Tập
									tin được chia sẻ</span>
						</a></li>
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/file', array('action'=>'list-not-share')) ?>"
							class="nav-link "> <i class="icon-docs"></i> <span class="title">Tập
									tin mới tải lên</span>
						</a></li>
						<li class="nav-item  "><a
							href="<?php echo $this->url('admin-control-panel/file', array('action'=>'add')) ?>"
							class="nav-link "> <i class="icon-doc"></i> <span class="title">Tải
									lên tập tin mới</span>
						</a></li>
					</ul></li>

				<li class="nav-item start "><a
					href="<?php echo $this->url('admin-control-panel/chat') ?>"
					class="nav-link nav-toggle"> <i class="fa fa-wechat"></i> <span
						class="title">Trao đổi</span>
				</a></li>
			</ul>
			<!-- END SIDEBAR MENU -->
			<!-- END SIDEBAR MENU -->
		</div>
		<!-- END SIDEBAR -->
	</div>
	<!-- END SIDEBAR -->