<?php echo $this->render('layout/admincp/header');?>
<?php echo $this->render('layout/admincp/left');?>


<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
	<!-- BEGIN CONTENT BODY -->
	<div class="page-content">

		<?php echo $this->content; ?>
	</div>
	<!-- END CONTENT BODY -->
</div>
<!-- END CONTENT -->


<?php echo $this->render('layout/admincp/right');?>
	<?php echo $this->render('layout/admincp/footer');?>