<!-- BEGIN FOOTER -->
        <div class="page-footer">
            <div class="page-footer-inner"> 2014 &copy; Metronic by keenthemes.
                <a href="http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes" title="Purchase Metronic just for 27$ and get lifetime updates for free" target="_blank">Purchase Metronic!</a>
            </div>
            <div class="scroll-to-top">
                <i class="icon-arrow-up"></i>
            </div>
        </div>
        <!-- END FOOTER -->
        <!--[if lt IE 9]>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/respond.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
        <!-- BEGIN CORE PLUGINS -->
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <?php echo $this->headScript(); ?>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="<?php echo $this->basePath(); ?>/assets/global/scripts/app.min.js" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript">
        $(document).ready(function(){
        	
//         	$("#infoEditor").ckeditor();
//         	$("#contentEditor").ckeditor();
//         	$('#category').jstree({
//         		'core': {
//                     "themes" : {
//                         "responsive": false
//                     },
//                     'data' : [
//                                 { "id": "2", "text": "Bài viết", "state": { "selected": false, "opened": true }, "icon" : "fa fa-folder icon-state-warning icon-lg","children": [{ "id": "31", "text": "Hướng Dẫn", "state": { "selected": false, "opened": true }, "icon" : "fa fa-folder icon-state-warning icon-lg","children": [{ "id": "32", "text": "Tìm hiểu", "state": { "selected": false, "opened": true }, "icon" : "fa fa-file icon-state-warning icon-lg",},{ "id": "33", "text": "Project", "state": { "selected": true, "opened": true }, "icon" : "fa fa-file icon-state-warning icon-lg",},]},{ "id": "34", "text": "Báo cáo", "state": { "selected": false, "opened": true }, "icon" : "fa fa-file icon-state-warning icon-lg",},{ "id": "35", "text": "Kiểm tra", "state": { "selected": false, "opened": true }, "icon" : "fa fa-file icon-state-warning icon-lg",},{ "id": "36", "text": "test", "state": { "selected": false, "opened": true }, "icon" : "fa fa-file icon-state-warning icon-lg",},]},
//                       	    ]
//                 },
//                 "types" : {
//                     "default" : {
//                         "icon" : "fa fa-folder icon-state-warning icon-lg"
//                     },
//                     "file" : {
//                         "icon" : "fa fa-file icon-state-warning icon-lg"
//                     }
//                 },
//                 "plugins": ["types"]
//             });

//         	$('#category').on("changed.jstree", function (e, data) {
//       		  $("#cate").val(data.selected);
//       		});
      		
//         	$('#tree_1').on('select_node.jstree', function(e,data) { 
//                 var link = $('#' + data.selected).find('a');
//                 if (link.attr("href") != "#" && link.attr("href") != "javascript:;" && link.attr("href") != "") {
//                     if (link.attr("target") == "_blank") {
//                         link.attr("href").target = "_blank";
//                     }
//                     document.location.href = link.attr("href");
//                     return false;
//                 }
//             });
            
//         	$('#tree_1').jstree({ 'core' : {
//         	    'data' : [
//         	       { "id" : "ajson1", "parent" : "#", "text" : "Simple root node" },
//         	       { "id" : "ajson2", "parent" : "#", "text" : "Root node 2" ,'state' : {'opened' : true, 'selected' : true}},
//         	       { "id" : "ajson3", "parent" : "ajson2", "text" : "Child 1", 'state' : { 'disabled': true}},
//         	       { "id" : "ajson4", "parent" : "ajson2", "text" : "Child 2", 'state' : { 'selected' : true}},
//         	    ]
//         	} });

        	
      		
//         	$('#using_json').jstree({ 'core' : {
//         	    'data' : [
//         	       'Simple root node',
//         	       {
//         	         'text' : 'Root node 2',
//         	         'state' : {
//         	           'opened' : true,
//         	           'selected' : true
//         	         },
//         	         'children' : [
//         	           { 'text' : 'Child 1' },
//         	           'Child 2'
//         	         ]
//         	      }
//         	    ]
//         	} });
        });
        </script>
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="<?php echo $this->basePath(); ?>/assets/layouts/layout/scripts/layout.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/layouts/layout/scripts/demo.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath(); ?>/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
        <!-- END THEME LAYOUT SCRIPTS -->
    </body>

</html>